blank_issues_enabled: false
contact_links:
  - name: 📚 Docs
    url: https://github.com/BetaHuhn/drkmd.js#-usage
    about: Checkout the drkmd-js documentation
  - name: 🚀 Feature Request
    url: https://github.com/BetaHuhn/drkmd-js/discussions/new?category=ideas
    about: Share ideas for new features
  - name: ❓ Ask a Question
    url: https://github.com/BetaHuhn/drkmd-js/discussions/new?category=q-a
    about: Ask the community for help