name: Publish NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: curl -s https://purge.jsdelivr.net/npm/drkmd-js/dist/drkmd-js.min.js
    - uses: BetaHuhn/ifttt-status@v1.0.2
      with:
        event: general
        key: ${{ secrets.IFTTT_TOKEN }}
        status: ${{ job.status }}
